### ISSUE TITLE
sth is wrong

### ISSUE THREAD

**Issue by sanruby77** [yerden/go-dpdk#30]
hello, Sir:
          After dpdk was installed, the examples app helloworld run well.
then build helloworld,get such an error,what should I do?

[root@localhost helloworld]# go build main.go
# github.com/yerden/go-dpdk/eal
../../eal/eal.go:141:9: could not determine kind of name for C.free

After added "#include <stdlib.h>" to the eal.go, It passed. Has any other way to avoid modifying the code?

btw:Does it support dpdk 22.11

**Comment by MajorAdam** [comment]
encounter same problem

**Comment by mmaveric** [comment]
Here is [PR](https://github.com/yerden/go-dpdk/pull/37) of DPDK 22.11 adoption

**Comment by yerden** [comment]
> Here is [PR](https://github.com/yerden/go-dpdk/pull/37) of DPDK 22.11 adoption

merged as of today, feel free to report any more issues.
